version: '3'
services:
  web:
    build: ./web
    depends_on:
      - app
    ports:
      - "8081:80"
      - "8080:443"
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
      - [your KEY configuration file path]:/etc/nginx/server.key
      - [your CRT configuration file path]:/etc/nginx/server.crt
      - ./data/html:/var/www/html

  app:
    image: php:7.4-fpm-alpine
    volumes:
      - ./data/html:/var/www/html
